// FreshFlow V0.7 product layer
(() => {
 const isAdmin=()=>['owner','admin'].includes(window.profile?.role);
 document.title='FreshFlow V0.7 | Superkleen Dry Cleaners';
 const ver=document.querySelector('.shopcard span:last-child'); if(ver) ver.textContent='Cloud V0.7';
 const nav=document.querySelector('.nav');
 if(nav){
   nav.insertAdjacentHTML('beforeend',`<button data-v07="production">Production <span id="prodBadge" class="badge">0</span></button><button data-v07="notifications">Notifications <span id="noteBadge" class="badge">0</span></button><button data-v07="accounts">Accounts</button>${isAdmin()?'<button data-v07="reports">Owner dashboard</button>':''}`);
   nav.querySelectorAll('[data-v07]').forEach(b=>b.onclick=()=>openV07(b.dataset.v07));
 }
 const app=document.querySelector('main')||document.querySelector('.main');
 const host=document.createElement('section');host.id='v07host';host.className='hidden'; if(app)app.appendChild(host);
 function hideBase(){document.querySelectorAll('main > section,.main > section').forEach(x=>{if(x!==host)x.classList.add('hidden')});host.classList.remove('hidden')}
 window.openV07=async function(view){hideBase();host.innerHTML='<div class="card"><div class="empty">Loading...</div></div>';if(view==='production')return production();if(view==='notifications')return notifications();if(view==='accounts')return accounts();if(view==='reports')return reports();}
 async function production(){await sb.rpc('refresh_operational_notifications');const {data:os}=await sb.from('orders').select('id,order_number,status,due_date,total,customers(name,phone)').not('status','in','("Collected","Cancelled")').order('due_date');const cols=['Received','Cleaning','Ready'];host.innerHTML=`<div class="pagehead"><div><h1>Production board</h1><p class="muted">Live work queue and overdue orders</p></div></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px">${cols.map(s=>`<div class="card"><h3>${s}</h3>${(os||[]).filter(o=>s==='Cleaning'?(!['Received','Ready'].includes(o.status)):o.status===s).map(o=>card(o)).join('')||'<div class="empty">Clear</div>'}</div>`).join('')}</div>`;const overdue=(os||[]).filter(o=>o.due_date&&o.due_date<new Date().toISOString().slice(0,10));prodBadge.textContent=overdue.length}
 function card(o){let late=o.due_date&&o.due_date<new Date().toISOString().slice(0,10);return `<div onclick="openOrder('${o.id}')" style="border:1px solid ${late?'#d9a2a2':'#e2e7e3'};padding:10px;border-radius:10px;margin:7px 0;cursor:pointer"><strong>#${o.order_number} · ${esc(o.customers?.name||'Customer')}</strong><div class="muted" style="font-size:10px">Due ${o.due_date||'Not set'} ${late?'· OVERDUE':''}</div></div>`}
 async function notifications(){await sb.rpc('refresh_operational_notifications');const {data:n}=await sb.from('notifications').select('*').eq('status','open').order('priority',{ascending:true}).order('created_at',{ascending:false});noteBadge.textContent=(n||[]).length;host.innerHTML=`<div class="pagehead"><div><h1>Notifications</h1><p class="muted">Items requiring attention</p></div></div><div class="card">${(n||[]).map(x=>`<div style="padding:11px;border-bottom:1px solid #eee"><strong>${esc(x.title)}</strong><div class="muted">${esc(x.body)}</div></div>`).join('')||'<div class="empty">Nothing needs attention.</div>'}</div>`}
 async function accounts(){const {data:c}=await sb.from('customers').select('id,name,phone,email,account_type,credit_limit,payment_terms_days').order('name');host.innerHTML=`<div class="pagehead"><div><h1>Customers & accounts</h1><p class="muted">Search history, commercial accounts and credit</p></div><input id="v07search" class="input" placeholder="Name, mobile or email"></div><div class="card"><div id="accountRows"></div></div>`;window.v07customers=c||[];renderAccounts('');v07search.oninput=()=>renderAccounts(v07search.value)}
 window.renderAccounts=function(q){q=(q||'').toLowerCase();let rows=v07customers.filter(c=>[c.name,c.phone,c.email].join(' ').toLowerCase().includes(q));accountRows.innerHTML=rows.map(c=>`<div style="display:flex;justify-content:space-between;align-items:center;padding:10px;border-bottom:1px solid #eee;cursor:pointer" onclick="customerHistoryV07('${c.id}')"><div><strong>${esc(c.name)}</strong><div class="muted">${esc(c.phone||'')} ${c.account_type==='commercial'?'· COMMERCIAL':''}</div></div><div>${c.account_type==='commercial'?`Credit ${money(c.credit_limit)} · ${c.payment_terms_days} days`:''}</div></div>`).join('')||'<div class="empty">No customers found.</div>'}
 window.customerHistoryV07=async function(id){let c=v07customers.find(x=>x.id===id);let {data:o}=await sb.from('orders').select('id,order_number,status,total,due_date,created_at').eq('customer_id',id).order('created_at',{ascending:false});modal.innerHTML=`<div class="modalhead"><div><h2>${esc(c.name)}</h2><div class="muted">${esc(c.phone||'')}</div></div><button class="btn secondary small" onclick="closeModal()">Close</button></div><h3 style="margin-top:14px">Order history</h3>${(o||[]).map(x=>`<div style="padding:9px;border-bottom:1px solid #eee;cursor:pointer" onclick="openOrder('${x.id}')"><strong>#${x.order_number}</strong> · ${x.status}<span style="float:right">${money(x.total)}</span></div>`).join('')||'<div class="empty">No orders</div>'}${isAdmin()?`<button class="btn secondary" style="margin-top:12px" onclick="commercialV07('${id}')">Commercial / credit settings</button>`:''}`;modalBack.classList.remove('hidden')}
 window.commercialV07=async function(id){let c=v07customers.find(x=>x.id===id);let type=prompt('Account type: retail or commercial',c.account_type||'retail');if(!type)return;let limit=Number(prompt('Credit limit',c.credit_limit||0));let terms=Number(prompt('Payment terms in days',c.payment_terms_days||0));let {error}=await sb.from('customers').update({account_type:type,credit_limit:limit,payment_terms_days:terms}).eq('id',id);if(error)return toast(error.message);closeModal();await accounts();toast('Account updated')}
 async function reports(){if(!isAdmin()){host.innerHTML='<div class="card"><div class="empty">Admin access required.</div></div>';return}let today=new Date(),from=new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10),to=today.toISOString().slice(0,10);let [{data:d},{data:expenses},{data:payments}]=await Promise.all([sb.rpc('admin_dashboard',{p_from:from,p_to:to}),sb.from('expenses').select('*').gte('expense_date',from).lte('expense_date',to),sb.from('payments').select('amount,method,created_at').gte('created_at',from+'T00:00:00')]);host.innerHTML=`<div class="pagehead"><div><h1>Owner dashboard</h1><p class="muted">${from} to ${to} · Admin only</p></div><button class="btn primary" onclick="addExpenseV07()">Add expense</button></div><div class="stats"><div class="stat"><span>Sales</span><strong>${money(d.sales)}</strong></div><div class="stat"><span>Orders</span><strong>${d.orders}</strong></div><div class="stat"><span>Expenses</span><strong>${money(d.expenses)}</strong></div><div class="stat"><span>Outstanding</span><strong>${money(d.outstanding)}</strong></div></div><div class="card" style="margin-top:10px"><h3>Operations</h3><div class="receiptline"><span>Overdue</span><strong>${d.overdue}</strong></div><div class="receiptline"><span>Ready for collection</span><strong>${d.ready}</strong></div><div class="receiptline"><span>Commercial debt</span><strong>${money(d.commercial_debt)}</strong></div><div class="receiptline"><span>Net after expenses</span><strong>${money(Number(d.sales)-Number(d.expenses))}</strong></div></div>`}
 window.addExpenseV07=async function(){let description=prompt('Expense description');if(!description)return;let amount=Number(prompt('Amount'));if(!(amount>0))return;let category=prompt('Category','General')||'General';let method=prompt('Payment method: cash, card or eft','cash')||'cash';let {error}=await sb.from('expenses').insert({business_id:profile.business_id,branch_id:profile.branch_id,description,amount,category,payment_method:method,created_by:profile.id});if(error)return toast(error.message);toast('Expense recorded');reports()}
 const oldOpenOrder=window.openOrder;window.openOrder=function(id){oldOpenOrder(id);setTimeout(()=>{let o=data.orders.find(x=>x.id===id);if(!o||!modal)return;if(o.status==='Ready'&&!modal.querySelector('[data-collect]'))modal.insertAdjacentHTML('beforeend',`<button data-collect class="btn primary" style="width:100%;margin-top:10px" onclick="confirmCollectV07('${id}')">Confirm collection</button>`);if(isAdmin()&&!modal.querySelector('[data-discount]'))modal.insertAdjacentHTML('beforeend',`<button data-discount class="btn secondary" style="margin-top:8px" onclick="discountV07('${id}',${Number(o.total)})">Discount</button>`);},0)}
 window.confirmCollectV07=async function(id){let who=prompt('Who is collecting this order?');if(!who)return;let {error}=await sb.rpc('confirm_order_collection',{p_order_id:id,p_collected_by:who});if(error)return toast(error.message);closeModal();await refreshAll();toast('Collection confirmed')}
 window.discountV07=async function(id,total){let amount=Number(prompt('Discount amount',0));if(amount<0||amount>total)return;let reason=prompt('Reason for discount');if(!reason)return;let {error}=await sb.rpc('apply_order_discount',{p_order_id:id,p_amount:amount,p_reason:reason});if(error)return toast(error.message);closeModal();await refreshAll();toast('Discount applied')}
 async function badges(){try{let {data:n}=await sb.rpc('refresh_operational_notifications');if(noteBadge)noteBadge.textContent=n||0}catch(e){}}
 badges();
})();
